# Retail Sales Data Audit
## Objectives
- Do proper audit of retial dataset
- Shape of data
- Datatypes 
- Properties of each observation(columns)
- Find total missing and duplicate values
- Number of unique values for each property
- Basic stats of numerical and categorical data
- Preview of first and last 5 rows

## Import Library and Set Up data

In [37]:
import pandas as pd

df = pd.read_csv("../data/raw/retail_sales_dataset.csv")

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

## Shape of Data

In [38]:
rows, cols = df.shape

print(f"Rows : {rows}")
print(f"Columns : {cols}")

Rows : 1000
Columns : 9

- Dataset has 1000 rows or observation
- and has 9 rows each showing properties of all observation

## Columns of Dataset

In [39]:
df.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='object')

- Columns are
    - Transaction ID
    - Date 
    - Customer ID
    - Gender
    - Age
    - Product Category
    - Quantity
    - Price per Unit
    - Total Amount

## Data types of All Columns

In [40]:
df.dtypes

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

- Here we have found out all data types of data for each columns of dataset
- Here "Date" should be of datetime data type if we want to do time based analysis

## Missing Values

In [41]:
df.isna().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

- As per the result we have no missing values/nan in our dataset

## Duplicate Rows

In [42]:
df.duplicated().sum()

0

- We have also noticed that we also do not have any duplicate rows.
- All rows are unique

## Number of Unique Values of columns

In [43]:
df.nunique()

Transaction ID      1000
Date                 345
Customer ID         1000
Gender                 2
Age                   47
Product Category       3
Quantity               4
Price per Unit         5
Total Amount          18
dtype: int64

## Basic Statistics

### Numerical

In [44]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

### Categorical

In [45]:
df.describe(include="object")

              Date Customer ID  Gender Product Category
count         1000        1000    1000             1000
unique         345        1000       2                3
top     2023-05-16     CUST001  Female         Clothing
freq            11           1     510              351

- Here we have done Basic stats of both
    - Numerical data
    - Categorical data

## First 5 rows

In [46]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

## Last 5 Rows

In [47]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

##  Conclusion
- Dataset consists of 1000 observation with 9 properties for each
- There is no missing and duplicate values in dataset
- We have found unique values for each columns
- We have found out basic stats for both numerical and categorical data.